name: Deploy Cloud SQL 

on:
  push:
    branches:
      - dev  
      - test
    paths:
      - '.github/workflows/cloud-sql.yml'
  pull_request:
    branches:
      - test
      - stage
      - prod
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev, test, stage, prod)'
        required: true
        type: choice
        options:
          - dev
          - test
          - stage
          - prod

jobs:
  cloud-sql:
    runs-on: gcp-arc-rsd
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Environment
        run: |
          case "${{ github.event_name }}" in
            "push")
              BRANCH="${{ github.ref_name }}"
              ;;
            "pull_request")
              BRANCH="${{ github.base_ref }}"
              ;;
            "workflow_dispatch")
              BRANCH="${{ github.event.inputs.environment }}"
              ;;
            *)
              echo "Unsupported event: ${{ github.event_name }}"
              exit 1
              ;;
          esac

          echo "Triggered by event: ${{ github.event_name }} on branch/environment: $BRANCH"

          case "$BRANCH" in
            "dev")
              echo "PROJECT_ID=prj-cus-qaw-dev-66576" >> $GITHUB_ENV
              echo "SERVICE_ACCOUNT=sa-use4-cloudsql-pipeline@prj-cus-qaw-dev-66576.iam.gserviceaccount.com" >> $GITHUB_ENV
              echo "WORKLOAD_IDENTITY_PROVIDER=projects/865276656676/locations/global/workloadIdentityPools/wif-pool/providers/wif-provider" >> $GITHUB_ENV
              echo "ENVIRONMENT=dev" >> $GITHUB_ENV
              echo "PSC_IP=10.141.132.5" >> $GITHUB_ENV
              echo "SUBNET=sn-ue4-cloudsql-psc-dev-1" >> $GITHUB_ENV
              ;;
            "test")
              echo "PROJECT_ID=prj-cus-qaw-tst-66576" >> $GITHUB_ENV
              echo "SERVICE_ACCOUNT=sa-use4-cloudsql-pipeline@prj-cus-qaw-tst-66576.iam.gserviceaccount.com" >> $GITHUB_ENV
              echo "WORKLOAD_IDENTITY_PROVIDER=projects/139527806265/locations/global/workloadIdentityPools/wif-pool/providers/wif-provider" >> $GITHUB_ENV
              echo "ENVIRONMENT=tst" >> $GITHUB_ENV
              echo "PSC_IP=10.141.135.5" >> $GITHUB_ENV
              echo "SUBNET=sn-ue4-cloudsql-psc-tst-1" >> $GITHUB_ENV
              ;;
            "stage")
              echo "PROJECT_ID=prj-shrd-stg-67236" >> $GITHUB_ENV
              echo "SERVICE_ACCOUNT=sa-composer-stage@prj-stage-123456.iam.gserviceaccount.com" >> $GITHUB_ENV
              echo "WORKLOAD_IDENTITY_PROVIDER=projects/123456789/locations/global/workloadIdentityPools/wif-pool/providers/wif-provider" >> $GITHUB_ENV
              echo "ENVIRONMENT=stg" >> $GITHUB_ENV
              echo "PSC_IP=10.141.135.5" >> $GITHUB_ENV
              echo "SUBNET=sn-ue4-cloudsql-psc-stg-1" >> $GITHUB_ENV
              ;;
            "prod")
              echo "PROJECT_ID=prj-shrd-prd-67236" >> $GITHUB_ENV
              echo "SERVICE_ACCOUNT=sa-composer-prod@prj-prod-123456.iam.gserviceaccount.com" >> $GITHUB_ENV
              echo "WORKLOAD_IDENTITY_PROVIDER=projects/123456789/locations/global/workloadIdentityPools/wif-prod/providers/wif-provider" >> $GITHUB_ENV
              echo "ENVIRONMENT=prd" >> $GITHUB_ENV
              echo "PSC_IP=10.141.135.5" >> $GITHUB_ENV
              echo "SUBNET=sn-ue4-cloudsql-psc-prd-1" >> $GITHUB_ENV
              ;;
            "main")
              echo "Final code storage—No deployment." && exit 0
              ;;
            *)
              echo "Branch not configured for deployment." && exit 1
              ;;
          esac

      - name: Check if Forwarding Rule Exists
        id: check-forwarding
        run: |
          if gcloud compute forwarding-rules describe qaw-app-db-${{ env.ENVIRONMENT }}-cloudsql \
            --project=prj-shrd-ntwk-3 --region=us-east4 > /dev/null 2>&1; then
            echo "FORWARDING_EXISTS=true" >> $GITHUB_ENV
          else
            echo "FORWARDING_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Forwarding Rule to Connect PSC to Service Attachment
        if: env.FORWARDING_EXISTS == 'false'
        run: |
          gcloud compute forwarding-rules create qaw-app-db-${{ env.ENVIRONMENT }}-cloudsql \
            --address=ip-npr-psc-qaw-app-db-${{ env.ENVIRONMENT }}-cloudsql \
            --project=prj-shrd-ntwk-3 \
            --region=us-east4 \
            --network=vpc-non-prod-shared-host \
            --target-service-attachment=${{ env.SERVICE_ATTACHMENT }} \
            --allow-psc-global-access
