name: Data Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  copy-composer-dag:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: qaw_milestone_4

      # Set Environment Variables
      - name: Set Environment Variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "PROJECT_ID=prj-prod-123456" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=sa-composer-prod@prj-prod-123456.iam.gserviceaccount.com" >> $GITHUB_ENV
            echo "WORKLOAD_IDENTITY_PROVIDER=projects/123456789/locations/global/workloadIdentityPools/wif-prod/providers/wif-provider" >> $GITHUB_ENV
            echo "GCS_BUCKET=gs://prod-composer-bucket/dags/" >> $GITHUB_ENV
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
            echo "PROJECT_ID=prj-prod-123456" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=sa-composer-prod@prj-prod-123456.iam.gserviceaccount.com" >> $GITHUB_ENV
            echo "WORKLOAD_IDENTITY_PROVIDER=projects/123456789/locations/global/workloadIdentityPools/wif-prod/providers/wif-provider" >> $GITHUB_ENV
            echo "GCS_BUCKET=gs://prod-composer-bucket/dags/" >> $GITHUB_ENV
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "stage" ]; then
            echo "PROJECT_ID=prj-prod-123456" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=sa-composer-prod@prj-prod-123456.iam.gserviceaccount.com" >> $GITHUB_ENV
            echo "WORKLOAD_IDENTITY_PROVIDER=projects/123456789/locations/global/workloadIdentityPools/wif-prod/providers/wif-provider" >> $GITHUB_ENV
            echo "GCS_BUCKET=gs://prod-composer-bucket/dags/" >> $GITHUB_ENV
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "PROJECT_ID=prj-shrd-dev-67236" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=sa-composer-us-4001@prj-shrd-dev-67236.iam.gserviceaccount.com" >> $GITHUB_ENV
            echo "WORKLOAD_IDENTITY_PROVIDER=projects/1046068350740/locations/global/workloadIdentityPools/wif-pool/providers/wif-provider" >> $GITHUB_ENV
            echo "GCS_BUCKET=gcs-duse4usw1-shrd-artifact-dev-67236/test_folder/" >> $GITHUB_ENV
            echo "PATH=dags/" >> $GITHUB_ENV
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV 
          fi

      - name: Google Authentication
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"

      - name: Upload all python file
        uses: google-github-actions/upload-cloud-storage@v2
        with:
         path: "${{ env.PATH }}"
         destination: "${{ env.GCS_BUCKET }}"
         glob: "*.py"

      - name: Upload sql folder 
        uses: google-github-actions/upload-cloud-storage@v2
        with:
         path: "${{ env.PATH }}/sql"
         destination: "${{ env.GCS_BUCKET }}"

      - name: Upload dag_config folder as per selected environment 
        uses: google-github-actions/upload-cloud-storage@v2
        with:
         path: "${{ env.PATH }}/dag_config/${{ env.ENVIRONMENT }}"
         destination: "${{ env.GCS_BUCKET }}"
