name: Deploy Dataform

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write  # Required for Workload Identity Federation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install Dataform CLI
        run: npm i -g @dataform/cli@^3.0.0-beta

      - name: Run Dataform
        run: |
          dataform run --tags DATASET
          dataform run --tags QADP
          dataform run --tags QADP_STAGING
