name: Create Tables in PostgreSQL

on:
  push:
    branches:
      - main  # Runs on push to main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-table:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: "prj-cus-qaw-dev-66576"
      SECRET_NAME: "projects/865276656676/secrets/qaw-app-db-dev-password"
      SQL_FILE: "APPLICATION.sql"
      DB_HOST: "qaw-app-db-dev.gcp.qdx.com"
      DB_PORT: "5432"
      DB_NAME: "qaw_app_db"
      DB_USER: "postgres"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Retrieve Database Password from Secrets
        run: echo "PGPASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Verify Connection to PostgreSQL
        run: |
          psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c "SELECT version();"

      - name: Execute SQL Script
        run: |
          psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -a -f $SQL_FILE
